### ISSUE TITLE
CLI: Full DSSE support

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#1111]
Right now, the `sigstore` CLI only has limited support for DSSE bundles: we support verifying them in `sigstore verify`, but not signing/generating via the CLI.

Some things we'll want to do:

- [x] #1115: We should support DSSE bundle generation and signing via the CLI. This will require some design thought on how best to integrate this with the current `sigstore sign` subcommand; two ideas:
    * `sigstore sign --attest` enables DSSE generation/signing, rather than the default `hashedrekord`
    * A new subcommand hierarchy, like `sigstore attest ...`, to mirror `cosign attest`
- [x] #1116: When verifying DSSE bundles with `sigstore verify ...` subcommands, we should support emitting the bundle's interior statement in a structured manner, for further processing.
    * One idea for doing this is to add a `--format=json` or similar flag across all of the verification subcommands, and have the subcommands emit only JSON in that case, e.g. `{"valid": true, "statement": {...}}`.
- [x] #1124: Generally improve our integration-level testing of the sigstore CLI

CC @facutuesca

**Comment by facutuesca** [comment]
I see that DSSE supports multiple artifacts (“subjects”) inside the envelope, each with a name and digest. But the current `sigstore sign` (non-DSSE) command will, given multiple input files, generate multiple bundle files, one for each input file.

Do we want the same behavior when using DSSE? That is, multiple input files -> multiple output bundles, even if a single DSSE envelope supports having multiple subjects? Or do we want to output a single sigstore bundle, that contains the DSSE envelope with multiple subjects?

**Comment by woodruffw** [comment]
> Do we want the same behavior when using DSSE? That is, multiple input files -> multiple output bundles, even if a single DSSE envelope supports having multiple subjects? Or do we want to output a single sigstore bundle, that contains the DSSE envelope with multiple subjects?

The former -- I think we want to maintain the 1:1 relationship between input and output files for now, even though DSSE bundles technically allow a 1:N relationship. My rationale for that is that fewer clients support that 1:N pattern, and the 1:1 pattern is more immediately applicable to use cases like Python packaging 🙂

**Comment by facutuesca** [comment]
Do we want to use the same default predicate type for the in-toto statement as `cosign`? i.e: `https://cosign.sigstore.dev/attestation/v1`

**Comment by woodruffw** [comment]
> Do we want to use the same default predicate type for the in-toto statement as `cosign`? i.e: `https://cosign.sigstore.dev/attestation/v1`.
> 
> 
> 

IIRC our DSSE signing API already uses a different predicate type (one that's not cosign specific) by default, so I *think* we should probably default to that. If I'm remembering right, I picked the current predicate default based on the GitHub Attestations' feature's default.

**Comment by woodruffw** [comment]
This is complete!
